---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DOCKER_TAG
  labels:
    app: $DOCKER_TAG
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $DOCKER_TAG
  template:
    metadata:
      labels:
        app: $DOCKER_TAG
    spec:
      containers:
        - name: $DOCKER_TAG
          image: $REGISTRY_URL/$DOCKER_TAG:$VERSION
          ports:
            - containerPort: <change_port_app>
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
          env:
            - name: MODE
              value: "local"
      volumes:
        - name: rabbitmq-storage
          hostPath:
            path: <change_path_local>


